In [27]:
import torch
import math


In [28]:
#empty
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-9.2018e+04,  3.0852e-41,  1.5975e-43,  1.3873e-43],
        [ 1.4574e-43,  6.4460e-44,  1.3873e-43,  1.5975e-43],
        [ 1.5554e-43,  1.6115e-43,  1.6115e-43,  0.0000e+00]])


In [29]:
#ones and random

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [30]:
# yield different tensors when needed like this
torch.manual_seed(11)
random = torch.rand(2, 3)
print(random)


random2 = torch.rand(2, 3)
print(random2)

tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])
tensor([[0.5831, 0.1284, 0.5721],
        [0.9248, 0.2693, 0.7825]])


In [31]:
# yield same
torch.manual_seed(11)
random = torch.rand(2, 3)
print(random)

torch.manual_seed(11)
random = torch.rand(2, 3)
print(random)


tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])
tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])


In [32]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)


#rand like easily creates a new tensor of the same shape as the tensor that we input in it
#like here x

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-9.2017e+04,  3.0852e-41,  9.8566e-01],
         [ 1.6840e-01,  5.8394e-01,  6.9360e-01]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0.5831, 0.1284, 0.5721],
         [0.9248, 0.2693, 0.7825]],

        [[0.2719, 0.4632, 0.7671],
         [0.5024, 0.1025, 0.7600]]])


.

Operations between tensor and scalar

In [33]:
twos = torch.ones(2, 2) * 2
sqrt2s = twos ** 0.5
half = twos / 2

print(twos) #original tensor
print(sqrt2s)
print(half)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
tensor([[1., 1.],
        [1., 1.]])


Operations between two tensors 

In [34]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

mult2 = twos * torch.tensor([[1, 2], [3, 4]])
print(mult2)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[2., 4.],
        [6., 8.]])


.

Broadcasting

In [35]:
#simple example of tensor broadcasting displaying 2 matrix mult

once = torch.rand(2, 4)
twice = once * (torch.ones(1, 4) * 2)

print(once)
print(twice)


tensor([[0.8035, 0.7653, 0.8709, 0.7231],
        [0.8364, 0.5820, 0.8395, 0.0595]])
tensor([[1.6071, 1.5306, 1.7418, 1.4461],
        [1.6729, 1.1640, 1.6789, 0.1190]])


.

Some extra math funcs to make work easy if ever required

In [36]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')

print(angles)
print(sines)
print(inverses)





Common functions:
tensor([[0.1370, 0.1151, 0.4757, 0.2601],
        [0.7550, 0.6748, 0.5124, 0.3237]])
tensor([[-0., -0., -0., 1.],
        [1., -0., -0., -0.]])
tensor([[-1., -1., -1.,  0.],
        [ 0., -1., -1., -1.]])
tensor([[-0.1370, -0.1151, -0.4757,  0.2601],
        [ 0.5000, -0.5000, -0.5000, -0.3237]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [37]:
# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements




Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [38]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.8847, 0.0763],
        [0.9900, 0.1944]])
tensor([[2.6542, 0.2288],
        [2.9701, 0.5833]])
torch.return_types.svd(
U=tensor([[-0.6604, -0.7509],
        [-0.7509,  0.6604]]),
S=tensor([4.0264, 0.2157]),
V=tensor([[-0.9892, -0.1463],
        [-0.1463,  0.9892]]))
