<a href="https://colab.research.google.com/github/Kaif10/Getting-started-with-Pytorch/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Getting started with basics of PyTorch

In [45]:
# importing libraries
import numpy as np
import torch

In [46]:
# initializing a numpy array
a = np.array(1)

# initializing a tensor (will create a tensor)
b = torch.tensor(1)

print(a)
print(b)

1
tensor(1)


In [27]:
type(a), type(b) #numpy array and tensor

(numpy.ndarray, torch.Tensor)

### Basic operations in numpy

In [28]:
# initializing two arrays
a = np.array(2)
b = np.array(1)

# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

3
-1
2
2.0


### Basic operations in PyTorch

In [29]:
# initializing two tensors
a = torch.tensor(2)
b = torch.tensor(1)
print(a,b)

# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

tensor(2) tensor(1)
tensor(3)
tensor(-1)
tensor(2)
tensor(2.)


### Matrix initialization

.

In [30]:
# matrix of zeros
a = np.zeros((3,3))
print(a)
print(a.shape)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [31]:
# matrix of zeros
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [32]:
# setting the random seed for pytorch
torch.manual_seed(42)

# matrix of random numbers
a = torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

### Matrix Operations

In [33]:
# setting the random seed for pytorch and initializing two tensors
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

# matrix addition
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication
print(torch.mm(a,b), '\n')

# matrix division
print(torch.div(a,b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


### Transpose of Matrix

In [34]:
# original matrix
print(a, '\n')

# matrix transpose
torch.t(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

### Concat Tensors

In [35]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)


# concatenating vertically
torch.cat((a,b))


tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [36]:
# concatenating horizontally
torch.cat((a,b),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [37]:
# setting the random seed for pytorch
torch.manual_seed(42)
# initializing tensor
a = torch.randn(2,4)
print(a)
a.shape



tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [38]:
# reshaping tensor
b = a.reshape(1,8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

In [39]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)


[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


.

Autograd Module
PyTorch uses a technique called automatic differentiation. It records all the operations that we are performing and replays it backward to compute gradients. This technique helps us to save time on each epoch as we are calculating the gradients on the forward pass itself.

Let’s look at an example to understand how the gradients are computed:

In [48]:
# initializing a tensor
a = torch.ones((2,2), requires_grad=True)
print(a)

#Here, we have initialized a tensor. 
#Specifying requires_grad as True will make sure that the gradients are stored for this particular tensor whenever we perform some operation on it. 
#Let’s now perform some operations on the defined tensor:

# performing operations on the tensor
b = a + 5
c = b.mean()
print(b,c)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


.

### First of all, we added 5 to all the elements of this tensor and then taken the mean of that tensor. We will first manually calculate the gradients and then verify that using PyTorch. We performed the following operations on a:

b = a + 5

c = mean(b) = Σ(a+5) / 4

Now, the derivative of c w.r.t. a will be ¼ and hence the gradient matrix will be 0.25. Let’s verify this using PyTorch:

In [49]:
# back propagating
c.backward()

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


### Various optimizers you can use for optimizing your neural network.
### Below examles are Adam and SGD

In [44]:
# importing the optim module
from torch import optim

# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)

# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)